# Generated by Django 2.1.5 on 2019-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
