# Generated by Django 2.1.5 on 2019-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='mail',
            new_name='email',
        ),
    ]
