# Generated by Django 2.1.5 on 2019-02-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190212_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='survey',
        ),
    ]
