# Generated by Django 2.1.1 on 2019-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='survey/video/questions/%Y/%m/%d/', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('select_image', 'Select Image'), ('integer', 'integer'), ('video', 'video')], default='text', max_length=200, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='template',
            field=models.CharField(blank=True, default='survey/forms/image_select.html', max_length=255, null=True, verbose_name='Template'),
        ),
    ]
