# Generated by Django 2.1.1 on 2019-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.CharField(blank=True, help_text='Here you can set the conditions on questions', max_length=250, null=True, verbose_name='Choices'),
        ),
    ]
