# Generated by Django 2.1.1 on 2019-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='constraints',
            field=models.CharField(blank=True, help_text='Here you can set the logic jumps', max_length=250, null=True, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Long text (multiple line)'), ('short-text', 'Short text (one line)'), ('radio', 'Radio Select'), ('select', 'Empty'), ('select-multiple', 'Select Multiple'), ('integer', 'Numeric'), ('image', 'Image')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
