# Generated by Django 2.1.1 on 2019-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190330_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='constraints',
        ),
        migrations.AddField(
            model_name='question',
            name='condition_script',
            field=models.CharField(blank=True, help_text='Here you can set the logic jumps', max_length=250, null=True, verbose_name='Logic Jumps'),
        ),
        migrations.AddField(
            model_name='question',
            name='conditional',
            field=models.BooleanField(default=0, verbose_name='Is it Conditional?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Long text (multiple line)'), ('short-text', 'Short text (one line)'), ('radio', 'Radio Select'), ('select', 'Empty'), ('select-multiple', 'Select Multiple'), ('integer', 'Numeric')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
