# Generated by Django 2.1.1 on 2019-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190330_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template'),
        ),
    ]
