# Generated by Django 2.1.1 on 2019-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190218_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='template',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select-multiple', 'Select Multiple'), ('select_image', 'Select Image'), ('integer', 'integer'), ('video', 'video')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
