# Generated by Django 2.1.1 on 2019-02-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190220_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vid_url',
        ),
    ]
