# Generated by Django 2.1.5 on 2019-02-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_survey'),
        ('survey', '0009_auto_20190212_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='company.Company', verbose_name='company'),
        ),
    ]
