# Generated by Django 2.1.1 on 2019-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_survey_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey/images/questions/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='survey',
            name='allows_multiple_interviews',
            field=models.BooleanField(blank=True, default=True, verbose_name='Allows multiple interviews'),
        ),
    ]
