# Generated by Django 2.1.1 on 2019-02-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('survey', '0011_auto_20190214_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.Video', verbose_name='video'),
        ),
        migrations.AddField(
            model_name='survey',
            name='video_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videocategories', to='video.VideoCategory', verbose_name='videocategory'),
        ),
    ]
