# Generated by Django 2.1.5 on 2019-02-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20181211_1908'),
        ('survey', '0011_auto_20190214_1939'),
    ]

    operations = [
    ]
