# Generated by Django 2.1.1 on 2019-02-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_question_vid_url'),
        ('survey', '0012_merge_20190215_1819'),
    ]

    operations = [
    ]
