# Generated by Django 2.1.1 on 2019-02-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190216_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='video.Video', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='video_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='video.VideoCategory', verbose_name='videocategory'),
        ),
    ]
