# Generated by Django 2.1.1 on 2019-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190216_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='video_cat',
        ),
    ]
