# Generated by Django 2.1.1 on 2019-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20190223_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('integer', 'integer'), ('select_image', 'Select Image'), ('add_date', 'Add Date')], default='text', max_length=200, verbose_name='Type'),
        ),
    ]
