# Generated by Django 2.1.1 on 2019-02-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190216_1534'),
        ('survey', '0014_remove_survey_video_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='video',
        ),
        migrations.AddField(
            model_name='survey',
            name='video_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='video.VideoCategory', verbose_name='videocategory'),
        ),
    ]
