# Generated by Django 2.1.1 on 2019-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190223_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='locations',
            field=models.CharField(default='karachi', max_length=100, verbose_name='Detect location'),
        ),
    ]
