# Generated by Django 2.1.1 on 2019-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_question_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='locations',
        ),
        migrations.AddField(
            model_name='question',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=24.83121231, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='question',
            name='long',
            field=models.DecimalField(decimal_places=6, default=67.83121231, max_digits=9, verbose_name='longitude'),
        ),
    ]
