# Generated by Django 2.1.1 on 2019-03-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20190326_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='question',
            name='long',
        ),
    ]
