# Generated by Django 2.1.1 on 2019-02-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Link to the video')),
                ('vid', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Video ID')),
                ('channelId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Channel ID')),
                ('type', models.IntegerField(default=0)),
                ('start', models.CharField(max_length=10, verbose_name='Start time')),
                ('end', models.CharField(max_length=10, verbose_name='End time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
            ],
            options={
                'verbose_name': 'videocategory',
                'verbose_name_plural': 'videocategories',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.VideoCategory'),
        ),
    ]
