# Generated by Django 2.1.1 on 2019-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190216_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Link to the video'),
        ),
    ]
