# Generated by Django 2.1.1 on 2019-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190216_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='Music Video', max_length=100, verbose_name='Name of the video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Link to the video'),
        ),
    ]
