# Generated by Django 2.1.1 on 2019-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190216_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link to the video'),
        ),
    ]
