# Generated by Django 2.1.1 on 2019-02-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20190216_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channelId',
        ),
        migrations.AlterField(
            model_name='video',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.VideoCategory', verbose_name='videocategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.IntegerField(default=0, verbose_name='Player'),
        ),
    ]
